### ISSUE TITLE
Export CSV & Export XML are not working

### ISSUE THREAD

**Issue by JoseGoncalves** [radiusone/a2billing#29]
In `Customers` -> `Add::Search` when I press the `Export CSV` or `Export XML` buttons the following error is triggered:

```
AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught TypeError: strlen(): Argument #1 ($string) must be of type string, array given in /var/www/html/a2billing/Public/admin/export_csv.php:55
```

**Comment by miken32** [comment]
I had meant to come back to this after commit addb0d0e but it was neglected. Export code should be sorted out shortly

**Comment by miken32** [comment]
Should be fixed by commits b03c0ee1 and 30d21aa1, let me know if not

**Comment by JoseGoncalves** [comment]
Did not work for me.

This is the CSV export output for Customers:
```
"Column 'id' in SELECT is ambiguous"
```
and for XML:
```xml
<?xml version="1.0"?>
<data>
  <header>
    <column name="error"/>
  </header>
  <records>
    <row>
      <column name="error">Column 'id' in SELECT is ambiguous</column>
    </row>
  </records>
</data>
```

**Comment by miken32** [comment]
Ratecard and customer exports are particularly problematic because they're user-defined so easy for users to put in wrong data. In this case other tables are being joined in. It's probably not reasonable to expect a user to be familiar with table names so I'll just put in a manual check for "id" and assume that they mean "cc_card.id".

**Comment by JoseGoncalves** [comment]
Using da6df5296bab1382213e9267dd7231078cf3561c I still can't export Customers.
I now have a different error:
> Unknown column 'cc_card.activated' in 'SELECT'

**Comment by miken32** [comment]
That column does not exist. Check `card_export_field_list` system setting and remove it.

**Comment by JoseGoncalves** [comment]
Done that... unable to test due to https://github.com/radiusone/a2billing/issues/32#issuecomment-3037027198

**Comment by JoseGoncalves** [comment]
Export is now working. Thanks!
