### ISSUE TITLE
Unable to edit customer information

### ISSUE THREAD

**Issue by JoseGoncalves** [radiusone/a2billing#32]
On `Customers -> Add:Search`, when I press the pencil button on a row in the table to edit that customer info, the customer form appears with "empty" data and there are a lot of errors on the reverse proxy log, similar to this one:

```
AH01071: Got error ' PHP Warning:  Trying to access array offset on value of type null in /var/www/html/a2billing/templates/EditForm.inc.php on line 109; PHP message: PHP Warning:  Trying to access array offset on value of type null in /var/www/html/a2billing/templates/EditForm.inc.php on line 109; PHP message: PHP Warning:  Trying to access array offset on value of type null in /var/www/html/a2billing/templates/EditForm.inc.php on line 109; PHP message: PHP Warning:  Trying to access array offset on value of type null in /var/www/html/a2billing/templates/EditForm.inc.php on line 109; PHP message: PHP Warning:  Trying to access array offset on value of type null in /var/www/html/a2billing/templates/EditForm.inc.php on line 109; PHP message: PHP Warning:  Trying to access array offset on value of type null in /var/www/html/a2billing/templates/EditForm.inc.php on line 109; PHP message: PHP Warning:  Trying to access array offset on value of type null in /var/www/html/a2billing/templates/EditForm.inc.php on line 109; PHP message: PHP Warning:  Trying to access array offset on value of type null in /var/www/html/a2billing/templates/EditForm.inc.php on line 109; PHP message: PHP Warning:  Trying to access array offset on value of type null in /var/www/html/a2billing/templates/EditForm.inc.php on line 109; PHP message: PHP Warning:  Trying to access array offset on value of type null in /var/www/html/a2billing/templates/EditForm.inc.php on line 109; PHP message: PHP Warning:  Trying to access array offset on value of type null in /var/www/html/a2billing/templates/EditForm.inc.php on line 109; PHP message: PHP Warning:  Trying to access array offset on value of type null in /var/www/html/a2billing/templates/EditForm.inc.php on line 109; PHP message: PHP Warning:  Trying to access array offset on value of type null in /var/www/html/a2billing/templates/EditForm.inc.php on line 109; PHP message: PHP Warning:  Trying to access array offset on value of type null in /var/www/html/a2billing/templates/EditForm.inc.php on line 109; PHP message: PHP Warning:  Trying to access array offset on value of type null in /var/www/html/a2billing/templates/EditForm.inc.php on line 109; PHP message: PHP Warning:  Trying to access array offset on value of type null in /var/www/html/a2billing/templates/EditForm.inc.php on line 109; PHP message: PHP Warning:  Trying to access array offset on value of type null in /var/www/html/a2billing/templates/EditForm.inc.php on line 109; PHP message: PHP Warning:  Trying to access array offset on value of type null in /var/www/html/a2billing/templates/EditForm.inc.php on line 109; PHP message: PHP Warning:  Trying to access array offset on value of type null in /var/www/html/a2billing/templates/EditForm.inc.php on line 109; PHP message: PHP Fatal error:  Uncaught TypeError: array_key_exists(): Argument #2 ($array) must be of type array, null given in /var/www/html/a2billing/templates/EditForm.inc.php:129\nStack trace:\n#0 /var/www/html/a2billing/templates/EditForm.inc.php(129): array_key_exists()\n#1 /var/www/html/a2billing/src/Forms/EditForm.php(24): require('...')\n#2 /var/www/html/a2billing/src/Forms/FormHandler.php(1914): A2billing\\Forms\\EditForm->__toString()\n#3 /var/www/html/a2billing/Public/admin/A2B_entity_card.php(622): A2billing\\Forms\\FormHandler->create_form()\n#4 {main}\n  thrown in /var/www/html/a2billing/templates/EditForm.inc.php on line 129', referer: https://st-3.inov.intranet/a2billing/A2B_entity_card.php
```

Nevertheless, clicking on the magnifying glass icon on a row presents the correct data.

**Comment by miken32** [comment]
Indeed. I'm certain that was working just a couple of days ago. 🚮

**Comment by JoseGoncalves** [comment]
Commit fe5d0dfa0621d96de99606c80bdf019642c6b079 made my customers list empty!
P.S. I have no permissions to reopen issues

**Comment by miken32** [comment]
It's working here. The only change there was to not join tables during edit. So no changes to list view behaviour at all.

**Comment by miken32** [comment]
What's the value of your `card_show_field_list` setting?

**Comment by JoseGoncalves** [comment]
> What's the value of your `card_show_field_list` setting?

`id,username,useralias,lastname,id_group,id_agent,credit,tariff,status`

**Comment by miken32** [comment]
Ok I saw the same thing when I changed my setting to match. Fixed now I hope. This code is too fragile

**Comment by JoseGoncalves** [comment]
Fixed it. Thanks!

**Comment by JoseGoncalves** [comment]
I've changed the `card_show_field_list` setting to `id,username,firstname,lastname,id_group,credit,status` and this was broken again. Is there a way to support dynamic changing of this setting or should I avoid changing it?

**Comment by JoseGoncalves** [comment]
Reverted to the old setting and still the same issue. On apache error log there is a lot of messages like this:
```
PHP message: PHP Warning:  Trying to access array offset on value of type null in /var/www/html/a2billing/templates/EditForm.inc.php on line 110
```

**Comment by miken32** [comment]
Yeah, not sure what changed there. Did I mention this code is too fragile? Will check it out

**Comment by miken32** [comment]
Hmm I actually noticed that last week (it's what triggered my comment on #39) and had a note to follow up on it. Just pushed 8dd98f3d which seems to fix it.

Those multi-select elements at the bottom of the card page were messing things up. That one page is the only place they're used, not surprising something involving them got missed.

**Comment by JoseGoncalves** [comment]
I confirm that commit 8dd98f3dcb94cd1460f9509d9b6f38e1d1ed5844 fixes this issue.
Thanks!
